<div class="alert alert-block alert-info" style="margin-top: 20px">

      
| Name | Description | Date
| :- |-------------: | :-:
|Reza Hashemi| PyTorch Model Basics 1st  | On 23rd of August 2019 | width="750" align="center"></a></p>
</div>

# Creating models
- nn.Module
- Data Types
- nn.Sequential

In [0]:
!pip3 install torch torchvision

In [0]:
import numpy as np
import pandas as pd
import torch, torchvision
torch.__version__

'1.1.0'

## 1. nn.Module
- When using Pytorch, machine learning (ML) models are constructed using ```torch.nn```, especially ```torch.nn.Module```.
  - Create a subclass of ```nn.Module```, and a model instance from that class
  - Documentation: [```torch.nn```](https://pytorch.org/docs/stable/nn.html)
 
- When implementing a ML model using ```torch.nn```, at least two functions should be specified in detail
  - ```__init__()```: define structure of the model and its parameters
  - ```forward```: define operation between layers (e.g., convolution, pooling, activation, ...)
  
 ```python
class MyModel(nn.Module):
    def __init__(self):
      super(MyModel, self).__init__()
      define model structure
    def forward(self, x):
      define operation
```

In [0]:
import torch.nn as nn

# creating a simplest linear regression model
class linear(nn.Module):
  def __init__(self):
    super(linear, self).__init__()
    self.dense = nn.Linear(5, 1)    # input features = 5, output features = 1
    
  def forward(self, x):
    x = self.dense(x)
    return x  

In [0]:
model = linear()
model

linear(
  (dense): Linear(in_features=5, out_features=1, bias=True)
)

In [0]:
# model parameters can be viewed with parameters()
# usually, parameters are passed onto optimizers (e.g., Adam) to perform gradient descent
for p in model.parameters():
  print(p)

Parameter containing:
tensor([[-0.1158, -0.1559,  0.4391, -0.3395,  0.2404]], requires_grad=True)
Parameter containing:
tensor([-0.1614], requires_grad=True)


In [0]:
# c.f. if you want to save parameters in a list...
nn.ParameterList(model.parameters())

ParameterList(
    (0): Parameter containing: [torch.FloatTensor of size 1x5]
    (1): Parameter containing: [torch.FloatTensor of size 1]
)

In [0]:
# state_dict() returns OrderedDict with layer names mapped to weights
model.state_dict()

OrderedDict([('dense.weight',
              tensor([[-0.1158, -0.1559,  0.4391, -0.3395,  0.2404]])),
             ('dense.bias', tensor([-0.1614]))])

In [0]:
# output from a single data instance can be generated
x = torch.randn(5, dtype = torch.float)   # generate a single data instance
print(x)
print(model(x))    # output result

tensor([0.9273, 0.2725, 1.3165, 0.3347, 2.1430])
tensor([0.6684], grad_fn=<AddBackward0>)


In [0]:
# output from multiple data instances can be generated
x = torch.randn(3, 5, dtype = torch.float)    # generate 3 random data instance
print(x)
print(model(x))     # output result

tensor([[-1.2600, -0.7596, -0.1252, -0.2723, -0.0267],
        [-0.3849,  1.5968, -0.8142,  1.1753, -0.8929],
        [-0.4453, -0.8134,  2.7589,  0.1609,  1.0995]])
tensor([[ 0.1340],
        [-1.3370],
        [ 1.4381]], grad_fn=<AddmmBackward>)


## 2. Data Types of Models
- In Pytorch, models have data types and they should be aligned with input data types
- Also, a model can be changed into GPU model. In this case, data type of input should be GPU-compatible as well.
```python
model.to(device)```

In [0]:
model = model.double()    # model has data type of double
print(x.dtype)            # x has data type of float
print(model(x))           # error

torch.float32


RuntimeError: ignored

In [0]:
model = model.float()     # now change model to float 
print(x.dtype)            # x has data type of float
print(model(x))           # no error

torch.float32
tensor([[ 0.1340],
        [-1.3370],
        [ 1.4381]], grad_fn=<AddmmBackward>)


In [0]:
device = torch.device("cuda")
model = model.to(device)
x = x.to(device)
print(model(x))

tensor([[ 0.1340],
        [-1.3370],
        [ 1.4381]], device='cuda:0', grad_fn=<AddmmBackward>)


## 3. nn.Sequential
- Sequential container in which modules can be added **in order**
  - Also, ```OrderedDict``` can be used as an input

In [0]:
# create a simple multi-layer perceptron
model = nn.Sequential(
          nn.Linear(5, 5),
          nn.ReLU(),
          nn.Linear(5, 1),
          nn.Sigmoid()
          )

In [0]:
x = torch.randn(5, dtype = torch.float)
model(x)

tensor([0.4720], grad_fn=<SigmoidBackward>)

In [0]:
# create MLP using ordereddict - same result as above
from collections import OrderedDict

model = nn.Sequential(OrderedDict([
    ("dense1", nn.Linear(5,5)),
    ("relu1", nn.ReLU()),
    ("dense2", nn.Linear(5,1)),
    ("relu2", nn.ReLU())
]))